### ISSUE TITLE
DateTime after REFRESH !!!

### ISSUE THREAD

**Issue by DR-DNK** [xreef/SimpleFTPServer#50]
Hey @xreef , I am using SimpleFTPServer library in Arduino ide and my controller ESP32S3 is FTP Server and FileZilla is FTP Client.

I am sending file from FileZilla to my esp32s3 which is transfered successfully . The only issue is that I have to refresh Filezilla everytime I upload a file to list the date and time on FileZilla .

Also the date and time which are shown in the FileZilla are correct , if I set the time with the help of NTP Server . But the date and time of the file in my PC is again the UTC time .

I am setting date and time with the help of callback function .

` void dateTime(uint16_t* date, uint16_t* time) {
      uint16_t year;
      uint8_t month, day, hour, minute, second;
   
      // User gets date and time from GPS or real-time clock here
   
      // return date using FS_DATE macro to format fields
      *date = FS_DATE(year, month, day);
   
      // return time using FS_TIME macro to format fields
      *time = FS_TIME(hour, minute, second);
   }`

Can you please guide me how to set date and time . Also tell me why I have to refresh FileZilla to show me the correct date and time ?

**Comment by xreef** [comment]
Hi DR-DNK,
I wrote an [article about set time timezone and DST](https://mischianti.org/network-time-protocol-ntp-timezone-and-daylight-saving-time-dst-with-esp8266-esp32-or-arduino/).

It's quite complete, and unlike the other tutorials you can find, this is a production solution (DST is needed to do a good job).

You can also simplify the process with these steps by using UTC.

From stack
`
# Set timezone to UTC
setenv("TZ", "GMT0",1);
tzset();

# Read in timezone of format 2023-03-14T00:00:00.000Z
struct tm tm;
sscanf(utc_time.c_str(), "%4d-%2d-%2dT%2d:%2d:%2d",
    &tm.tm_year,
    &tm.tm_mon,
    &tm.tm_mday,
    &tm.tm_hour,
    &tm.tm_min,
    &tm.tm_sec
);

# mktime is expecting tm_year & tm_mon based off year since 1900 and months since January
tm.tm_year -= 1900;
tm.tm_mon--;

time_t epoch = mktime(&tm);

# Set to the new timezone we want & convert it
setenv("TZ","PST8PDT",1);
tzset();

struct tm* out_tm;
out_tm = localtime(&epoch);

# Print it out
char out_str[15];
strftime(out_str,sizeof(out_str),""%A, %B %d %Y %I:%M:%S"",out_tm);
Serial.printf("Converted time is: %s\n",out_str);

`

Bye Renzo
